
# # exception handling
# try:
#  a = int(input("enter a number :"))
#  print(a)
# except Exception as e:
#  print(e)
# print("thank you")  




# # particular exception handling
# try:
#  a = int(input("enter a number :"))
#  print(a)
# except ValueError as v:
#  print(v) 
# print("thank you")  



















